services:
  brok:
    build:
      context: .
    image: brok:local
    container_name: brok-app
    pull_policy: never
    env_file:
      - .env
    
    environment:
      - QT_QPA_PLATFORM=xcb
      - DISPLAY=${DISPLAY:-:0}

    volumes:
      - ./brok:/app/brok
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    network_mode: host
    restart: "no"